FGCenter/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace FGCenter.Models
{
    public class Post
    {
        [Key]
        public int PostId { get; set; }

        public string Title { get; set; }


        public string Text { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DatePosted { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime EditedDate { get; set; }

        [Required]
        public string UserId { get; set; }

        public ApplicationUser User { get; set; }

        
        public Game Game { get; set; }

        [ForeignKey("Games")]
        public int GameId { get; set; }
    }
}

FGCenter/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FGCenter.Data;
using FGCenter.Models;
using Microsoft.AspNetCore.Identity;
using FGCenter.Models.ViewModels;

namespace FGCenter.Controllers
{
    public class CommentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly UserManager<ApplicationUser> _userManager;

        public Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        public CommentsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

        public async Task<IActionResult> YourComments()
        {
            ApplicationUser user = await GetCurrentUserAsync();

            return View(await _context.Comment.Where(p => p.UserId == user.Id).ToListAsync());
        }

        // GET: Comments/Create
        public IActionResult Create(int id)
        {
            var model = new CommentCreateViewModel();
            var post =  _context.Post
                .Where(c => c.PostId == id).FirstOrDefault();
            model.Post = post;
            model.Post.PostId = post.PostId;

            return View(model);
        }

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, CommentCreateViewModel model)
        {

            ModelState.Remove("Comment.User");
            ModelState.Remove("Comment.UserId");

            ApplicationUser user = await GetCurrentUserAsync();

            model.Comment.User = user;
            model.Comment.UserId = user.Id;
            model.Comment.PostId = id;

            if (ModelState.IsValid)
            {
                _context.Add(model.Comment);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Posts", new { id = model.Comment.PostId });
            }
            

            return View(model);
        }

        // GET: Comments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _context.Comment.FindAsync(id);

            if (comment == null)
            {
                return NotFound();
            }
 
            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, [Bind("CommentId,Text,DatePosted,EditedDate,PostId,UserId")] Comment comment)
        {
            if (id != comment.CommentId)
            {
                return NotFound();
            }

            ModelState.Remove("User");
            ModelState.Remove("UserId");

            ApplicationUser user = await GetCurrentUserAsync();

            var CommentBeingTracked = await _context.Comment
                .Where(c => c.CommentId == id).FirstOrDefaultAsync();

            CommentBeingTracked.Text = comment.Text;

            CommentBeingTracked.EditedDate = DateTime.Now;
            

            if (user != null && ModelState.IsValid && CommentBeingTracked.UserId == user.Id)
            {
                try
                {
                    _context.Update(CommentBeingTracked);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CommentExists(comment.CommentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", "Posts", new { id = CommentBeingTracked.PostId });
            }

            return View(CommentBeingTracked);
        }

        // GET: Comments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _context.Comment
                .Include(c => c.Post)
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.CommentId == id);

            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            ApplicationUser user = await GetCurrentUserAsync();
            var comment = await _context.Comment.FindAsync(id);
            if (user!= null && user.Id == comment.UserId)
            {
                _context.Comment.Remove(comment);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Games");
            }
            else
            {
                return RedirectToAction("Index", "Games");
            }

        }

        private bool CommentExists(int id)
        {
            return _context.Comment.Any(e => e.CommentId == id);
        }
    }
}

FGCenter/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FGCenter.Data;
using FGCenter.Models;
using FGCenter.Models.ViewModels;
using Microsoft.AspNetCore.Identity;

namespace FGCenter.Controllers
{
    public class PostsController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        private readonly ApplicationDbContext _context;

        public PostsController(ApplicationDbContext context,
                                UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

        public async Task<IActionResult> YourPosts()
        {
            ApplicationUser user = await GetCurrentUserAsync();

            return View(await _context.Post.Where(p => p.UserId == user.Id).ToListAsync());
        }

        // GET: Posts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var model = new PostDetailViewModel();

            var getpost = await _context.Post
                 .Include(p=> p.User)
                 .Include(p => p.Game)
                 .Where(p => p.PostId == id).FirstOrDefaultAsync();

            model.Post = getpost;

            var GroupedComment = await _context.Comment
                .Include(p => p.Post)
                .Include(p => p.User)
                .Where(p => p.PostId == id)
                .ToListAsync();
     

            model.GroupedComments = GroupedComment;

            //GET USER

            ApplicationUser user = await GetCurrentUserAsync();
            model.User = user;

            return View(model);
        }

        // GET: Posts/Create
        public IActionResult Create()
        {
            ViewData["GameId"] = new SelectList(_context.Game, "GameId", "Name");
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PostId,Title,Text,DatePosted,EditedDate,UserId,GameId")] Post post)
        {

            ModelState.Remove("User");
            ModelState.Remove("UserId");

            ApplicationUser user = await GetCurrentUserAsync();

            post.User = user;
            post.UserId = user.Id;

            if (ModelState.IsValid)
            {
                _context.Add(post);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Details), new { id = post.PostId });
            }


            return View(post);
        }

        // GET: Posts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Post.FindAsync(id);
            if (post == null)
            {
                return NotFound();
            }
            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PostId,Title,Text,DatePosted,EditedDate,UserId,GameId")] Post post)
        {
            if (id != post.PostId)
            {
                return NotFound();
            }

            ModelState.Remove("User");
            ModelState.Remove("UserId");

            ApplicationUser user = await GetCurrentUserAsync();

            
            var PostBeingTrack = await _context.Post
                .Where(p => p.PostId == id).FirstOrDefaultAsync();

            PostBeingTrack.EditedDate = DateTime.Now;
            PostBeingTrack.Text = post.Text;
            PostBeingTrack.Title = post.Title;

            if (user != null && ModelState.IsValid && PostBeingTrack.UserId == user.Id)
            {
                try
                {
                    _context.Update(PostBeingTrack);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostExists(PostBeingTrack.PostId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Details), new { id = post.PostId });

            }

            return View(PostBeingTrack);
        }

        // GET: Posts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Post
                .Include(p => p.Game)
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.PostId == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            ApplicationUser user = await GetCurrentUserAsync();
            var post = await _context.Post.FindAsync(id);

            if(user != null && user.Id == post.UserId)
            {
                _context.Post.Remove(post);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Games");
            }
            else
            {
                return RedirectToAction("Index", "Games");
            }
        }

        private bool PostExists(int id)
        {
            return _context.Post.Any(e => e.PostId == id);
        }
    }
}

FGCenter/Views/Posts/Create.cshtml
@model FGCenter.Models.Post

@{
    ViewData["Title"] = "Create";
}


<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Text" class="control-label"></label>
                <textarea asp-for="Text" class="form-control" id="url"></textarea>
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Game.Name" class="control-label"></label>
                <select asp-for="GameId" class="form-control" asp-items="ViewBag.GameId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" onclick="convert();" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Games" asp-action="Index">Back to Main Page</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FGCenter/Views/Posts/Delete.cshtml
@model FGCenter.Models.Post

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Post</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DatePosted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DatePosted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EditedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EditedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Game)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Game.Name)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PostId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-controller="Games" asp-route-id="@Model.GameId" asp-action="Details">Back</a>
    </form>
</div>

FGCenter/Views/Posts/Details.cshtml
@model FGCenter.Models.ViewModels.PostDetailViewModel

@{
    ViewData["Title"] = "Details";
}

<div>
    <div class="postboxdiv">
        <table class="postbox">

            <tr class="textboxforposts">
                
                <h1 class="postheader">
                    @Html.DisplayFor(modelItem => modelItem.Post.Title)
                </h1>
                <td class="postbox1">
                    @Html.DisplayFor(modelItem => modelItem.Post.Text)
                </td>
                <td class="userbox">
                    <img width="50" src="@Html.DisplayFor(modelItem => modelItem.Post.User.ImageUrl)" />
                    @Html.DisplayFor(modelItem => modelItem.Post.User.UserName)
                    <p class="card-text"><small class="text-muted">@Html.DisplayFor(modelItem => modelItem.Post.User.DateCreated)</small></p>
                </td>

            </tr>
        </table>

        <p>

            @if (Model.User != null)
            {
                <a asp-controller="Comments" asp-route-id="@Model.Post.PostId" asp-action="Create">Submit A Comment</a>

            }
            <div class="userbuttons1">
                @if (Model.User != null && Model.Post.User.Id == Model.User.Id)
                {
                    <a class="backbutton" asp-controller="Posts" asp-route-id="@Model.Post.PostId" asp-action="Edit">
                        <img width="40" src="~/images/edit.png" />
                    </a>
                }
                <a class="backbutton back" asp-controller="Games" asp-route-id="@Model.Post.Game.GameId" asp-action="Details">
                    <img width="33" src="~/images/back.jpg" />
                </a>
            </div>
        </p>
    </div>
    <hr style="border-color:white" />
    <div class="postboxdiv">

        @foreach (Comment p in Model.GroupedComments)
        {
            <table class="postbox1 threadbox">
                <tbody>
                    <tr class="textboxforpost">

                        <td class="postbox1 commentpostbox">


                            @Html.DisplayFor(modelItem => p.Text)
                            <p>

                            <small class="text-muted datetext">@Html.DisplayFor(modelItem => p.DatePosted)</small>
                            </p>

                        <td class="userbox">
                            <img width="40" src="@Html.DisplayFor(modelItem => p.User.ImageUrl)" />


                            @Html.DisplayFor(modelItem => p.User.UserName)
                            <p class="card-text"><small class="text-muted">@Html.DisplayFor(modelItem => p.User.DateCreated)</small></p>
                        <div class="buttonarea">

                            @if (Model.User != null && p.User.Id == Model.User.Id)
                            {
                                <a class="userbuttons" asp-controller="Comments" asp-action="Edit" asp-route-id="@p.CommentId">
                                    <img width="40" src="~/images/edit.png" />
                                </a>
                                <a class="userbuttons" asp-controller="Comments" asp-action="Delete" asp-route-id="@p.CommentId">
                                    <img width="27" src="~/images/delete.png" />
                                </a>
                            }
                        </div>
                        </td>

                        </td>
                    </tr>
                </tbody>
            </table>
        }

    </div>
</div>

FGCenter/Views/Posts/Edit.cshtml
@model FGCenter.Models.Post

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Post</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PostId" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Text" class="control-label"></label>
                <textarea  asp-for="Text" class="form-control"></textarea>
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Posts" asp-route-id="@Model.PostId" asp-action="Details">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FGCenter/Views/Posts/YourPosts.cshtml
@model IEnumerable<FGCenter.Models.Post>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                Post
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatePosted)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EditedDate)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Game)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Text)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DatePosted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EditedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Game.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.PostId">Edit</a> |
                <a asp-action="Delete" asp-route-id="@item.PostId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>