FGCenter/Models/Game.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FGCenter.Models
{
    public class Game
    {
        public int GameId { get; set; }

        public string Name { get; set; }

        public string ImageUrl { get; set; }

        public string ShortenedName { get; set; }

        public string DeveloperName { get; set; }
    }
}

FGCenter/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FGCenter.Data;
using FGCenter.Models;
using FGCenter.Models.ViewModels;
using Microsoft.AspNetCore.Identity;

namespace FGCenter.Controllers
{
    public class GamesController : Controller
    {

        private readonly UserManager<ApplicationUser> _userManager;

        public Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        private readonly ApplicationDbContext _context;

        public GamesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

        // GET: Games
        public async Task<IActionResult> Index()
        {
            var model = new GameIndexViewModel();

            //get users
            ApplicationUser user = await GetCurrentUserAsync();
            model.User = user;

            //get post counts
            var PostsCount = await (
                from g in _context.Game
                from p in _context.Post.Where(co => g.GameId == co.GameId).DefaultIfEmpty()
                group new { g, p } by new { g.GameId, g.Name, g.ImageUrl } into grouped
                select new GamesWithPostCountViewModel
                {
                    PostCount = grouped.Where(gr => gr.p != null).Count(),
                    Game = new Game
                    {
                        GameId = grouped.Key.GameId,
                        Name = grouped.Key.Name,
                        ImageUrl = grouped.Key.ImageUrl,
                    }
                }).ToListAsync();

            model.GamesWithPostCount = PostsCount;

            return View(model);
        }

        // GET: Games/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //CREATE A NEW GameDetailViewModel
            var model = new GameDetailViewModel();

            //GET GAME INFO
            var game = await _context.Game
                .Where(g => g.GameId == id).FirstOrDefaultAsync();

                model.Game = game;

            //GET COMMENT COUNT
            var CommentCount = await (
                from p in _context.Post.Where(po => po.GameId == id)
                from c in _context.Comment.Where(co => p.PostId == co.PostId).DefaultIfEmpty()
                group new { p, c } by new { p.PostId, p.Title, p.DatePosted, p.User, p.User.UserName, p.User.Id } into grouped
                select new PostWithCommentCountViewModel
                {
                    NumberOfComments = grouped.Where(gr => gr.c != null).Count(),
                    Post = new Post
                    {
                        PostId = grouped.Key.PostId,
                        Title = grouped.Key.Title,
                        DatePosted = grouped.Key.DatePosted,
                        User = new ApplicationUser
                        {
                            Id = grouped.Key.User.Id,
                            UserName = grouped.Key.User.UserName
                        }
                    }
                }).ToListAsync();

            model.PostsWithCommentCount = CommentCount;

            //GET USER

            ApplicationUser user = await GetCurrentUserAsync();
            model.User = user;

            return View(model);
           
        }

        // GET: Games/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Games/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GameId,Name,ImageUrl,DeveloperName")] Game game)
        {
            ApplicationUser user = await GetCurrentUserAsync();

            if (user != null && user.UserName == "admin@admin.com" && ModelState.IsValid)
            {
                _context.Add(game);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(game);
        }

        // GET: Games/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = await _context.Game.FindAsync(id);
            if (game == null)
            {
                return NotFound();
            }
            return View(game);
        }

        // POST: Games/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GameId,Name,ImageUrl,DeveloperName")] Game game)
        {
            if (id != game.GameId)
            {
                return NotFound();
            }
            ApplicationUser user = await GetCurrentUserAsync();

            if (user != null && user.UserName =="admin@admin.com" && ModelState.IsValid)
            {
                try
                {
                    _context.Update(game);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GameExists(game.GameId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(game);
        }

        private bool GameExists(int id)
        {
            return _context.Game.Any(e => e.GameId == id);
        }
    }
}

FGCenter/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FGCenter.Data;
using FGCenter.Models;
using FGCenter.Models.ViewModels;
using Microsoft.AspNetCore.Identity;

namespace FGCenter.Controllers
{
    public class PostsController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        private readonly ApplicationDbContext _context;

        public PostsController(ApplicationDbContext context,
                                UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

        public async Task<IActionResult> YourPosts()
        {
            ApplicationUser user = await GetCurrentUserAsync();

            return View(await _context.Post.Where(p => p.UserId == user.Id).ToListAsync());
        }

        // GET: Posts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var model = new PostDetailViewModel();

            var getpost = await _context.Post
                 .Include(p=> p.User)
                 .Include(p => p.Game)
                 .Where(p => p.PostId == id).FirstOrDefaultAsync();

            model.Post = getpost;

            var GroupedComment = await _context.Comment
                .Include(p => p.Post)
                .Include(p => p.User)
                .Where(p => p.PostId == id)
                .ToListAsync();
     

            model.GroupedComments = GroupedComment;

            //GET USER

            ApplicationUser user = await GetCurrentUserAsync();
            model.User = user;

            return View(model);
        }

        // GET: Posts/Create
        public IActionResult Create()
        {
            ViewData["GameId"] = new SelectList(_context.Game, "GameId", "Name");
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PostId,Title,Text,DatePosted,EditedDate,UserId,GameId")] Post post)
        {

            ModelState.Remove("User");
            ModelState.Remove("UserId");

            ApplicationUser user = await GetCurrentUserAsync();

            post.User = user;
            post.UserId = user.Id;

            if (ModelState.IsValid)
            {
                _context.Add(post);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Details), new { id = post.PostId });
            }


            return View(post);
        }

        // GET: Posts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Post.FindAsync(id);
            if (post == null)
            {
                return NotFound();
            }
            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PostId,Title,Text,DatePosted,EditedDate,UserId,GameId")] Post post)
        {
            if (id != post.PostId)
            {
                return NotFound();
            }

            ModelState.Remove("User");
            ModelState.Remove("UserId");

            ApplicationUser user = await GetCurrentUserAsync();

            
            var PostBeingTrack = await _context.Post
                .Where(p => p.PostId == id).FirstOrDefaultAsync();

            PostBeingTrack.EditedDate = DateTime.Now;
            PostBeingTrack.Text = post.Text;
            PostBeingTrack.Title = post.Title;

            if (user != null && ModelState.IsValid && PostBeingTrack.UserId == user.Id)
            {
                try
                {
                    _context.Update(PostBeingTrack);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostExists(PostBeingTrack.PostId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Details), new { id = post.PostId });

            }

            return View(PostBeingTrack);
        }

        // GET: Posts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Post
                .Include(p => p.Game)
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.PostId == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            ApplicationUser user = await GetCurrentUserAsync();
            var post = await _context.Post.FindAsync(id);

            if(user != null && user.Id == post.UserId)
            {
                _context.Post.Remove(post);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Games");
            }
            else
            {
                return RedirectToAction("Index", "Games");
            }
        }

        private bool PostExists(int id)
        {
            return _context.Post.Any(e => e.PostId == id);
        }
    }
}

FGCenter/Views/Games/Create.cshtml
@model FGCenter.Models.Game

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Game</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DeveloperName" class="control-label"></label>
                <input asp-for="DeveloperName" class="form-control" />
                <span asp-validation-for="DeveloperName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShortenedName" class="control-label"></label>
                <input asp-for="ShortenedName" class="form-control" />
                <span asp-validation-for="ShortenedName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FGCenter/Views/Games/Details.cshtml
@model FGCenter.Models.ViewModels.GameDetailViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>@Html.DisplayFor(model => model.Game.Name)</h1>  <img width="80" src="@Html.DisplayFor(model => model.Game.ImageUrl)" />


<div>
    @if (Model.User != null)
    {
    <hr />
        <p>
            <a asp-controller="Posts" asp-action="Create">Submit A Post</a>
        </p>
    }
    <table class="table">
        <tbody>
            @foreach (var p in Model.PostsWithCommentCount)
            {
            <tr>
                <td style="font-size:large">
                    @Html.DisplayFor(modelItem => p.Post.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => p.Post.DatePosted)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => p.Post.User.UserName)
                </td>
                <td>
                    @if (p.NumberOfComments == 1)
                    {
                        <a asp-controller="Posts" asp-action="Details" asp-route-id="@p.Post.PostId"> @Html.DisplayFor(modelItem => p.NumberOfComments) Comment</a>
                    }
                    else
                    {
                        <a asp-controller="Posts" asp-action="Details" asp-route-id="@p.Post.PostId"> @Html.DisplayFor(modelItem => p.NumberOfComments) Comments</a>
                    }
                    @if (Model.User != null && p.Post.User.Id == Model.User.Id)
                    {
                        <div>
                            <a asp-controller="Posts" asp-action="Delete" asp-route-id="@p.Post.PostId">Delete</a> |
                            <a asp-controller="Posts" asp-action="Edit" asp-route-id="@p.Post.PostId">Edit</a>
                        </div>
                    }
                </td>
            </tr>
             }
                
            </tbody>
        </table>
</div>

FGCenter/Views/Games/Edit.cshtml
@model FGCenter.Models.Game

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Game</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="GameId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DeveloperName" class="control-label"></label>
                <input asp-for="DeveloperName" class="form-control" />
                <span asp-validation-for="DeveloperName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FGCenter/Views/Games/Index.cshtml
@model FGCenter.Models.ViewModels.GameIndexViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>All Games</h1>

<p>
    @if (Model.User != null && Model.User.UserName == "admin@admin.com")
    {
        <a asp-action="Create">Create New</a>
    }
</p>
<table class="table">
    <tbody>
@foreach (var p in Model.GamesWithPostCount)
{
        <tr>
            <td>
                <img width="100" src="@Html.DisplayFor(modelItem => p.Game.ImageUrl)" />
            </td>
            <td style="font-size:larger">
                @Html.DisplayFor(modelItem => p.Game.Name)
            </td>
            <td >
                @Html.DisplayFor(modelItem => p.PostCount)
            </td>
            <td>
                @if (Model.User != null && Model.User.UserName == "admin@admin.com")
                {
                    @Html.ActionLink("Edit", "Edit", new { id = p.Game.GameId })
                }

                @Html.ActionLink("Details", "Details", new { id = p.Game.GameId })
            </td>
        </tr>
}
    </tbody>
</table>