FGCenter/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FGCenter.Data;
using FGCenter.Models;
using FGCenter.Models.ViewModels;
using Microsoft.AspNetCore.Identity;

namespace FGCenter.Controllers
{
    public class GamesController : Controller
    {

        private readonly UserManager<ApplicationUser> _userManager;

        public Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        private readonly ApplicationDbContext _context;

        public GamesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

        // GET: Games
        public async Task<IActionResult> Index()
        {
            var model = new GameIndexViewModel();

            //get users
            ApplicationUser user = await GetCurrentUserAsync();
            model.User = user;

            //get post counts
            var PostsCount = await (
                from g in _context.Game
                from p in _context.Post.Where(co => g.GameId == co.GameId).DefaultIfEmpty()
                group new { g, p } by new { g.GameId, g.Name, g.ImageUrl } into grouped
                select new GamesWithPostCountViewModel
                {
                    PostCount = grouped.Where(gr => gr.p != null).Count(),
                    Game = new Game
                    {
                        GameId = grouped.Key.GameId,
                        Name = grouped.Key.Name,
                        ImageUrl = grouped.Key.ImageUrl,
                    }
                }).ToListAsync();

            model.GamesWithPostCount = PostsCount;

            return View(model);
        }

        // GET: Games/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //CREATE A NEW GameDetailViewModel
            var model = new GameDetailViewModel();

            //GET GAME INFO
            var game = await _context.Game
                .Where(g => g.GameId == id).FirstOrDefaultAsync();

                model.Game = game;

            //GET COMMENT COUNT
            var CommentCount = await (
                from p in _context.Post.Where(po => po.GameId == id)
                from c in _context.Comment.Where(co => p.PostId == co.PostId).DefaultIfEmpty()
                group new { p, c } by new { p.PostId, p.Title, p.DatePosted, p.User, p.User.UserName, p.User.Id } into grouped
                select new PostWithCommentCountViewModel
                {
                    NumberOfComments = grouped.Where(gr => gr.c != null).Count(),
                    Post = new Post
                    {
                        PostId = grouped.Key.PostId,
                        Title = grouped.Key.Title,
                        DatePosted = grouped.Key.DatePosted,
                        User = new ApplicationUser
                        {
                            Id = grouped.Key.User.Id,
                            UserName = grouped.Key.User.UserName
                        }
                    }
                }).ToListAsync();

            model.PostsWithCommentCount = CommentCount;

            //GET USER

            ApplicationUser user = await GetCurrentUserAsync();
            model.User = user;

            return View(model);
           
        }

        // GET: Games/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Games/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GameId,Name,ImageUrl,DeveloperName")] Game game)
        {
            ApplicationUser user = await GetCurrentUserAsync();

            if (user != null && user.UserName == "admin@admin.com" && ModelState.IsValid)
            {
                _context.Add(game);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(game);
        }

        // GET: Games/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = await _context.Game.FindAsync(id);
            if (game == null)
            {
                return NotFound();
            }
            return View(game);
        }

        // POST: Games/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GameId,Name,ImageUrl,DeveloperName")] Game game)
        {
            if (id != game.GameId)
            {
                return NotFound();
            }
            ApplicationUser user = await GetCurrentUserAsync();

            if (user != null && user.UserName =="admin@admin.com" && ModelState.IsValid)
            {
                try
                {
                    _context.Update(game);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GameExists(game.GameId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(game);
        }

        private bool GameExists(int id)
        {
            return _context.Game.Any(e => e.GameId == id);
        }
    }
}

FGCenter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head style="color:white">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FGCenter</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="color:white">
    <header>
        <nav  style="background-color:darkred" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Games" asp-action="Index">
                    <img width="40" src="~/images/logo.png" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white font-weight-bold" asp-area="" asp-controller="Games" asp-action="Details" asp-route-id="1">SFV</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white font-weight-bold" asp-area="" asp-controller="Games" asp-action="Details" asp-route-id="2">DBFZ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white font-weight-bold" asp-area="" asp-controller="Games" asp-action="Details" asp-route-id="3">MK11</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white font-weight-bold" asp-area="" asp-controller="Games" asp-action="Details" asp-route-id="4">SSBU</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white font-weight-bold" asp-area="" asp-controller="Games" asp-action="Details" asp-route-id="5">T7</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white font-weight-bold" asp-area="" asp-controller="Games" asp-action="Details" asp-route-id="7">TMNT</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>